### PUT request to update patient
PUT localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "address": "3, Santiago road, Bernabue",
  "dateOfBirth": "1967-09-10",
  "name": "olamide",
  "registeredDate": "1978-06-12"
}
###